//! C6 paired hidden-subfield witness replay.
//!
//! The unchanged T1 prover is executed once on coordinate zero with the
//! opt-in [`volta_mac::C6SubfieldWitnessAudit`] sidecar. Coordinate one is
//! then generated by replaying the exact public correlation schedule against
//! the same reconstructed plaintexts. Model inference and the old proof are
//! not rerun. This is a witness-construction seam, not a succinct proof or a
//! client-verifiable commitment.

use std::fmt;
use volta_mac::{
    C6SubfieldWitnessAudit, CorrScheduleAudit, CorrScheduleKind, CorrScheduleRole,
    CorrelationStream,
};

pub type C6SubfieldDigest = [u8; 32];

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct C6SubfieldError(String);

impl C6SubfieldError {
    fn new(message: impl Into<String>) -> Self {
        Self(message.into())
    }
}

impl fmt::Display for C6SubfieldError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for C6SubfieldError {}

/// Two independent prover-only subfield witnesses authenticating one
/// canonical plaintext schedule.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct C6PairedSubfieldWitness {
    tape_ids: [C6SubfieldDigest; 2],
    coordinates: [C6SubfieldWitnessAudit; 2],
    schedule_digest: C6SubfieldDigest,
    pair_digest: C6SubfieldDigest,
}

impl C6PairedSubfieldWitness {
    pub fn new(
        tape_ids: [C6SubfieldDigest; 2],
        coordinates: [C6SubfieldWitnessAudit; 2],
        schedule: &CorrScheduleAudit,
    ) -> Result<Self, C6SubfieldError> {
        if tape_ids[0] == [0; 32] || tape_ids[1] == [0; 32] || tape_ids[0] == tape_ids[1] {
            return Err(C6SubfieldError::new(
                "C6 paired subfield witness requires two distinct nonzero tape identities",
            ));
        }
        coordinates[0].validate_against(schedule).map_err(C6SubfieldError::new)?;
        coordinates[1].validate_against(schedule).map_err(C6SubfieldError::new)?;
        if coordinates[0].len() != coordinates[1].len() {
            return Err(C6SubfieldError::new(
                "C6 paired subfield coordinates have different leaf counts",
            ));
        }
        if coordinates[0].witness_digest == coordinates[1].witness_digest {
            return Err(C6SubfieldError::new(
                "C6 paired subfield coordinates reuse the same secret witness",
            ));
        }
        for index in 0..coordinates[0].len() {
            if coordinates[0].plaintext(index) != coordinates[1].plaintext(index) {
                return Err(C6SubfieldError::new(format!(
                    "C6 paired subfield plaintext differs at leaf {index}"
                )));
            }
        }
        if coordinates[0].plaintext_digest != coordinates[1].plaintext_digest {
            return Err(C6SubfieldError::new("C6 paired subfield plaintext digests differ"));
        }
        let mut hasher =
            blake3::Hasher::new_derive_key("volta/proto/c6/paired-subfield-witness/v1");
        hasher.update(&schedule.digest);
        for coordinate in 0..2 {
            hasher.update(&tape_ids[coordinate]);
            hasher.update(&coordinates[coordinate].witness_digest);
            hasher.update(&coordinates[coordinate].correction_digest);
            hasher.update(&coordinates[coordinate].plaintext_digest);
        }
        let pair_digest = *hasher.finalize().as_bytes();
        Ok(Self { tape_ids, coordinates, schedule_digest: schedule.digest, pair_digest })
    }

    pub fn tape_ids(&self) -> [C6SubfieldDigest; 2] {
        self.tape_ids
    }

    pub fn coordinates(&self) -> &[C6SubfieldWitnessAudit; 2] {
        &self.coordinates
    }

    pub fn leaf_count(&self) -> usize {
        self.coordinates[0].len()
    }

    pub fn schedule_digest(&self) -> C6SubfieldDigest {
        self.schedule_digest
    }

    pub fn pair_digest(&self) -> C6SubfieldDigest {
        self.pair_digest
    }

    pub fn plaintext_digest(&self) -> C6SubfieldDigest {
        self.coordinates[0].plaintext_digest
    }

    pub fn correction_digests(&self) -> [C6SubfieldDigest; 2] {
        [self.coordinates[0].correction_digest, self.coordinates[1].correction_digest]
    }
}

/// Generate coordinate one without repeating model inference/proving.
///
/// The secondary stream must be fresh and independently seeded/backed. Every
/// full-field draw is replayed as well, even though this function returns only
/// the subfield witness, so its public allocation schedule is byte-identical
/// to coordinate zero. The reserved historical PCS tail is capacity padding,
/// not part of this source schedule.
pub fn replay_c6_subfield_coordinate(
    primary: &C6SubfieldWitnessAudit,
    schedule: &CorrScheduleAudit,
    secondary: &mut CorrelationStream,
) -> Result<C6SubfieldWitnessAudit, C6SubfieldError> {
    primary.validate_against(schedule).map_err(C6SubfieldError::new)?;
    secondary.enable_c6_subfield_witness_collection().map_err(C6SubfieldError::new)?;

    for draw in &schedule.draws {
        let count = usize::try_from(draw.count)
            .map_err(|_| C6SubfieldError::new("C6 replay draw count exceeds usize"))?;
        match (draw.kind, draw.role) {
            (CorrScheduleKind::Subfield, CorrScheduleRole::DirectCorrection) => {
                let correlations = secondary.draw_subs(draw.domain, count);
                let first = usize::try_from(draw.global_offset)
                    .map_err(|_| C6SubfieldError::new("C6 replay offset exceeds usize"))?;
                let end = first
                    .checked_add(count)
                    .ok_or_else(|| C6SubfieldError::new("C6 replay range overflows"))?;
                if end > primary.len() {
                    return Err(C6SubfieldError::new(
                        "C6 replay subfield range exceeds the primary witness",
                    ));
                }
                let corrections = correlations
                    .iter()
                    .enumerate()
                    .map(|(offset, correlation)| {
                        primary
                            .plaintext(first + offset)
                            .expect("validated C6 primary plaintext range")
                            .sub(correlation.r)
                            .value()
                    })
                    .collect::<Vec<_>>();
                secondary
                    .record_c6_subfield_corrections(draw.domain, &corrections)
                    .map_err(C6SubfieldError::new)?;
            }
            (CorrScheduleKind::FullField, CorrScheduleRole::DirectCorrection) => {
                let _ = secondary.draw_fulls(draw.domain, count);
            }
            (CorrScheduleKind::FullField, CorrScheduleRole::ProductMask) => {
                if count != 1 {
                    return Err(C6SubfieldError::new(
                        "C6 replay ProductClosure mask count is not one",
                    ));
                }
                let triples = usize::try_from(draw.product_triples)
                    .map_err(|_| C6SubfieldError::new("C6 replay triple count exceeds usize"))?;
                let _ = secondary.draw_product_mask(draw.domain, triples);
            }
            (CorrScheduleKind::Subfield, CorrScheduleRole::ProductMask) => {
                return Err(C6SubfieldError::new(
                    "C6 replay encountered a subfield ProductClosure mask",
                ));
            }
        }
    }

    let replayed_schedule = secondary
        .schedule_audit()
        .ok_or_else(|| C6SubfieldError::new("C6 replay lacks its schedule audit"))?;
    if replayed_schedule != *schedule {
        return Err(C6SubfieldError::new(
            "C6 secondary coordinate allocation schedule differs from coordinate zero",
        ));
    }
    let secondary_witness =
        secondary.finish_c6_subfield_witness_collection().map_err(C6SubfieldError::new)?;
    for index in 0..primary.len() {
        if primary.plaintext(index) != secondary_witness.plaintext(index) {
            return Err(C6SubfieldError::new(format!("C6 replay changed plaintext leaf {index}")));
        }
    }
    Ok(secondary_witness)
}

#[cfg(test)]
mod tests {
    use super::*;
    use volta_field::Fp;

    fn coordinate(seed: u8, plaintexts: &[u64]) -> (CorrScheduleAudit, C6SubfieldWitnessAudit) {
        let mut stream = CorrelationStream::new([seed; 32]);
        stream.enable_c6_subfield_witness_collection().unwrap();

        let first = stream.draw_subs(10, 2);
        let first_corrections = first
            .iter()
            .enumerate()
            .map(|(index, source)| (Fp::new(plaintexts[index]) - source.r).value())
            .collect::<Vec<_>>();
        stream.record_c6_subfield_corrections(10, &first_corrections).unwrap();
        let _ = stream.draw_fulls(11, 2);
        let second = stream.draw_subs(12, 3);
        let second_corrections = second
            .iter()
            .enumerate()
            .map(|(index, source)| (Fp::new(plaintexts[index + 2]) - source.r).value())
            .collect::<Vec<_>>();
        stream.record_c6_subfield_corrections(12, &second_corrections).unwrap();
        let _ = stream.draw_product_mask(13, 7);

        let schedule = stream.schedule_audit().unwrap();
        let witness = stream.finish_c6_subfield_witness_collection().unwrap();
        (schedule, witness)
    }

    #[test]
    fn second_coordinate_replays_schedule_and_same_plaintext_without_model_rerun() {
        let plaintexts = [1, 2, 3, 4, 5];
        let (schedule, primary) = coordinate(0x61, &plaintexts);
        let mut secondary_stream = CorrelationStream::new([0x62; 32]);
        let secondary =
            replay_c6_subfield_coordinate(&primary, &schedule, &mut secondary_stream).unwrap();
        let pair =
            C6PairedSubfieldWitness::new([[1; 32], [2; 32]], [primary, secondary], &schedule)
                .unwrap();
        assert_eq!(pair.leaf_count(), plaintexts.len());
        assert_eq!(pair.schedule_digest(), schedule.digest);
        assert_ne!(pair.correction_digests()[0], pair.correction_digests()[1]);
        assert_ne!(pair.pair_digest(), [0; 32]);
        for (index, &expected) in plaintexts.iter().enumerate() {
            assert_eq!(pair.coordinates()[0].plaintext(index), Some(Fp::new(expected)));
            assert_eq!(pair.coordinates()[1].plaintext(index), Some(Fp::new(expected)));
        }
    }

    #[test]
    fn paired_subfield_witness_rejects_tape_reuse_schedule_and_plaintext_changes() {
        let (schedule, first) = coordinate(0x71, &[1, 2, 3, 4, 5]);
        let (_, changed_plaintext) = coordinate(0x72, &[1, 2, 3, 4, 6]);
        assert!(C6PairedSubfieldWitness::new(
            [[1; 32], [2; 32]],
            [first.clone(), changed_plaintext],
            &schedule,
        )
        .is_err());
        assert!(C6PairedSubfieldWitness::new(
            [[1; 32], [1; 32]],
            [first.clone(), first.clone()],
            &schedule,
        )
        .is_err());
        assert!(C6PairedSubfieldWitness::new(
            [[1; 32], [2; 32]],
            [first.clone(), first.clone()],
            &schedule,
        )
        .is_err());

        let mut reordered = schedule.clone();
        reordered.draws.swap(0, 1);
        assert!(C6PairedSubfieldWitness::new(
            [[1; 32], [2; 32]],
            [first.clone(), first],
            &reordered,
        )
        .is_err());
    }
}
