#!/usr/bin/env python3
"""Recompute the non-credit C41NISC1 / FS+CI-VOLE analytic screen."""

import math


PROOF_CAP = 70_000_000
CURRENT_PROOF = 67_831_020
CELLS = 3_110_400
PACKED_D_BYTES = 2 * CELLS
PACKED_E_BYTES = CELLS // 8

C4_SETUP = 38_371_465
SETUP_CAP = 3 * C4_SETUP
CURRENT_TYPED_SETUP = 2_074_954

C4_PROVER = 4.104595717
PROVER_RATIO_CAP = 1.30
CURRENT_PROVER = 7.942478252

CURRENT_VERIFIER_ACCOUNTED = 3.322998133
CURRENT_PEAK_DEVICE = 18_056_184_148
DEVICE_CAP = 30_000_000_000

BASE_SOUNDNESS = 78.80929487390853
BASE_WEIGHT_ZK = 120.0170064253057
SECURITY_FLOOR = 78.0

BRIDGES = 640
# Static call-graph derivation only; an instrumented production record is still
# required before this may be treated as a measured census.
STATIC_SPARSE_ENTRIES = 8_294_400

LOGVOLE_RING_DEGREE = 8_192
LOGVOLE_Q_BITS = 220
LOGVOLE_QUERY_BYTES = LOGVOLE_RING_DEGREE * LOGVOLE_Q_BITS // 8
LOGVOLE_PUBLISHED_SETUP_APPROX_BYTES = 38_000_000
LOGVOLE_PUBLISHED_LABELS_PER_SECOND_16C = 12_900_000
LOGVOLE_PADDED_LABELS = 4_194_304
LOGVOLE_BASE_INSTANCES_FOR_FP2 = 2

AUTH_GARBLING_BYTES_PER_AND = 256
SUCCINCT_ARITHMETIC_BITS_PER_GATE_LOWER_BOUND = 64
FP2_BYTES = 16


def union_bits(*bits: float) -> float:
    return -math.log2(sum(2**-value for value in bits))


STRICT_PROOF_HEADROOM = PROOF_CAP - CURRENT_PROOF - 1
REPLACEABLE_PACKED_BYTES = PACKED_D_BYTES + PACKED_E_BYTES
DIRECT_CIVOLE_PROOF_AT_PUBLISHED_QUERY = (
    CURRENT_PROOF - REPLACEABLE_PACKED_BYTES + LOGVOLE_QUERY_BYTES
)
DIRECT_CIVOLE_PROOF_AT_8X_QUERY = (
    CURRENT_PROOF - REPLACEABLE_PACKED_BYTES + 8 * LOGVOLE_QUERY_BYTES
)

SETUP_BUDGET_IF_TYPED_SETUP_REPLACED = SETUP_CAP - C4_SETUP
TWO_BASE_SEMIHONEST_SETUP = (
    C4_SETUP + LOGVOLE_BASE_INSTANCES_FOR_FP2 * LOGVOLE_PUBLISHED_SETUP_APPROX_BYTES
)
ONE_FP2_MALICIOUS_LOW_SETUP = C4_SETUP + 2 * LOGVOLE_PUBLISHED_SETUP_APPROX_BYTES
ONE_FP2_MALICIOUS_HIGH_SETUP = C4_SETUP + 8 * LOGVOLE_PUBLISHED_SETUP_APPROX_BYTES
TWO_BASE_MALICIOUS_LOW_SETUP = (
    C4_SETUP
    + 2
    * LOGVOLE_BASE_INSTANCES_FOR_FP2
    * LOGVOLE_PUBLISHED_SETUP_APPROX_BYTES
)

PROVER_CAP_SECONDS = PROVER_RATIO_CAP * C4_PROVER
CURRENT_REQUIRED_REPAIR_SECONDS = CURRENT_PROVER - PROVER_CAP_SECONDS
ALLOWED_SUCCESSOR_OVERHEAD_SECONDS = PROVER_CAP_SECONDS - C4_PROVER
TWO_BASE_SEMIHONEST_16C_SECONDS = (
    LOGVOLE_BASE_INSTANCES_FOR_FP2
    * LOGVOLE_PADDED_LABELS
    / LOGVOLE_PUBLISHED_LABELS_PER_SECOND_16C
)
TWO_BASE_MALICIOUS_LOW_16C_SECONDS = 2 * TWO_BASE_SEMIHONEST_16C_SECONDS
ONE_FP2_SEMIHONEST_16C_SECONDS = (
    LOGVOLE_PADDED_LABELS / LOGVOLE_PUBLISHED_LABELS_PER_SECOND_16C
)
ONE_FP2_MALICIOUS_LOW_16C_SECONDS = 2 * ONE_FP2_SEMIHONEST_16C_SECONDS
ONE_FP2_MALICIOUS_HIGH_16C_SECONDS = 8 * ONE_FP2_SEMIHONEST_16C_SECONDS
ONE_FP2_OUTPUT_STATE_BYTES_PER_PARTY = LOGVOLE_PADDED_LABELS * FP2_BYTES

AUTH_GARBLING_AND_CAP = STRICT_PROOF_HEADROOM // AUTH_GARBLING_BYTES_PER_AND
SUCCINCT_ONE_MUL_PER_CELL_BYTES = (
    CELLS * SUCCINCT_ARITHMETIC_BITS_PER_GATE_LOWER_BOUND // 8
)
SUCCINCT_ONE_MUL_PER_SPARSE_ENTRY_BYTES = (
    STATIC_SPARSE_ENTRIES * SUCCINCT_ARITHMETIC_BITS_PER_GATE_LOWER_BOUND // 8
)
LINEAR_FP2_ENCODING_BYTES = CELLS * FP2_BYTES

MIN_NEW_ERROR_BITS = -math.log2(2**-SECURITY_FLOOR - 2**-BASE_SOUNDNESS)
COMPOSED_AT_SIGMA_40 = union_bits(BASE_SOUNDNESS, 40)
COMPOSED_AT_SIGMA_80 = union_bits(BASE_SOUNDNESS, 80)
COMPOSED_AT_SIGMA_96 = union_bits(BASE_SOUNDNESS, 96)
WEIGHT_ZK_AT_SIGMA_96 = union_bits(BASE_WEIGHT_ZK, 96)

assert STRICT_PROOF_HEADROOM == 2_168_979
assert REPLACEABLE_PACKED_BYTES == 6_609_600
assert LOGVOLE_QUERY_BYTES == 225_280
assert DIRECT_CIVOLE_PROOF_AT_PUBLISHED_QUERY == 61_446_700
assert DIRECT_CIVOLE_PROOF_AT_8X_QUERY == 63_023_660
assert DIRECT_CIVOLE_PROOF_AT_8X_QUERY < PROOF_CAP
assert SETUP_BUDGET_IF_TYPED_SETUP_REPLACED == 76_742_930
assert TWO_BASE_SEMIHONEST_SETUP == 114_371_465 < SETUP_CAP
assert ONE_FP2_MALICIOUS_LOW_SETUP == 114_371_465 < SETUP_CAP
assert ONE_FP2_MALICIOUS_HIGH_SETUP == 342_371_465 > SETUP_CAP
assert TWO_BASE_MALICIOUS_LOW_SETUP == 190_371_465 > SETUP_CAP
assert math.isclose(PROVER_CAP_SECONDS, 5.3359744321)
assert math.isclose(CURRENT_REQUIRED_REPAIR_SECONDS, 2.6065038199)
assert TWO_BASE_MALICIOUS_LOW_16C_SECONDS > ALLOWED_SUCCESSOR_OVERHEAD_SECONDS
assert ONE_FP2_MALICIOUS_LOW_16C_SECONDS < ALLOWED_SUCCESSOR_OVERHEAD_SECONDS
assert ONE_FP2_MALICIOUS_HIGH_16C_SECONDS > ALLOWED_SUCCESSOR_OVERHEAD_SECONDS
assert ONE_FP2_OUTPUT_STATE_BYTES_PER_PARTY == 67_108_864
assert AUTH_GARBLING_AND_CAP == 8_472
assert SUCCINCT_ONE_MUL_PER_CELL_BYTES == 24_883_200 > STRICT_PROOF_HEADROOM
assert SUCCINCT_ONE_MUL_PER_SPARSE_ENTRY_BYTES == 66_355_200
assert LINEAR_FP2_ENCODING_BYTES == 49_766_400
assert 79.21 < MIN_NEW_ERROR_BITS < 79.23
assert COMPOSED_AT_SIGMA_40 < SECURITY_FLOOR
assert COMPOSED_AT_SIGMA_80 > SECURITY_FLOOR
assert COMPOSED_AT_SIGMA_96 > SECURITY_FLOOR
assert WEIGHT_ZK_AT_SIGMA_96 > SECURITY_FLOOR
assert CURRENT_PEAK_DEVICE < DEVICE_CAP

print(
    {
        "credit": False,
        "proof_execution_performed": False,
        "pod_contacted": False,
        "private_challenge_census_in_fs_hybrid": 0,
        "cells": CELLS,
        "bridges": BRIDGES,
        "static_sparse_entries_unmeasured": STATIC_SPARSE_ENTRIES,
        "strict_current_proof_headroom_bytes": STRICT_PROOF_HEADROOM,
        "replaceable_packed_d_e_bytes": REPLACEABLE_PACKED_BYTES,
        "direct_civole_proof_one_query_bytes": DIRECT_CIVOLE_PROOF_AT_PUBLISHED_QUERY,
        "direct_civole_proof_eight_query_bytes": DIRECT_CIVOLE_PROOF_AT_8X_QUERY,
        "setup_cap_bytes": SETUP_CAP,
        "replacement_setup_budget_bytes": SETUP_BUDGET_IF_TYPED_SETUP_REPLACED,
        "two_base_semihonest_setup_approx_bytes": TWO_BASE_SEMIHONEST_SETUP,
        "one_fp2_malicious_low_setup_approx_bytes": ONE_FP2_MALICIOUS_LOW_SETUP,
        "one_fp2_malicious_high_setup_approx_bytes": ONE_FP2_MALICIOUS_HIGH_SETUP,
        "two_base_malicious_low_setup_approx_bytes": TWO_BASE_MALICIOUS_LOW_SETUP,
        "prover_cap_seconds": PROVER_CAP_SECONDS,
        "current_required_repair_seconds": CURRENT_REQUIRED_REPAIR_SECONDS,
        "allowed_successor_overhead_seconds": ALLOWED_SUCCESSOR_OVERHEAD_SECONDS,
        "two_base_semihonest_16c_projection_seconds": TWO_BASE_SEMIHONEST_16C_SECONDS,
        "two_base_malicious_low_16c_projection_seconds": TWO_BASE_MALICIOUS_LOW_16C_SECONDS,
        "one_fp2_semihonest_16c_projection_seconds": ONE_FP2_SEMIHONEST_16C_SECONDS,
        "one_fp2_malicious_low_16c_projection_seconds": ONE_FP2_MALICIOUS_LOW_16C_SECONDS,
        "one_fp2_malicious_high_16c_projection_seconds": ONE_FP2_MALICIOUS_HIGH_16C_SECONDS,
        "one_fp2_output_state_bytes_per_party": ONE_FP2_OUTPUT_STATE_BYTES_PER_PARTY,
        "authenticated_garbling_and_cap": AUTH_GARBLING_AND_CAP,
        "succinct_garbling_cell_lower_bound_bytes": SUCCINCT_ONE_MUL_PER_CELL_BYTES,
        "succinct_garbling_sparse_lower_bound_bytes": SUCCINCT_ONE_MUL_PER_SPARSE_ENTRY_BYTES,
        "linear_fp2_encoding_bytes": LINEAR_FP2_ENCODING_BYTES,
        "minimum_new_statistical_security_bits": MIN_NEW_ERROR_BITS,
        "composed_soundness_sigma40_bits": COMPOSED_AT_SIGMA_40,
        "composed_soundness_sigma80_bits": COMPOSED_AT_SIGMA_80,
        "composed_soundness_sigma96_bits": COMPOSED_AT_SIGMA_96,
        "composed_weight_zk_sigma96_bits": WEIGHT_ZK_AT_SIGMA_96,
        "verifier_gate": "not numerically defined; 3.322998133 s is a provisional no-regression screen only",
        "ruling": "generic NISC rejected; transparent malicious Fp2 LogVOLE remains conditional research survivor",
    }
)
